# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEbCCiM-jmely4V7zXWhoSAjLpqB87Er
"""

!pip install --force-reinstall python-telegram-bot==20.8 google-genai gspread oauth2client nest_asyncio requests

import os
import logging
import asyncio
import requests
from google import genai
from telegram import Update
from telegram.ext import Application, MessageHandler, filters, ContextTypes
import nest_asyncio

# =====================================================================
# ⚠️ မိမိ၏ Key အစစ်အမှန်များကို အောက်ပါ မျက်တောင်ကွင်း " " ထဲတွင် အတိအကျ ဖြည့်ပေးပါဗျာ
# =====================================================================
TELEGRAM_TOKEN = "8906970805:AAEICOzteFW2rkZ8-IESt7MTW7CRyaKARkk"
GEMINI_API_KEY = "AQ.Ab8RN6Jn4fQafHo9pvYZr_NE4KO-dBURVbGHdBQeccFaG7nlxQ"
GOOGLE_WEBAPP_URL = "https://script.google.com/macros/s/AKfycbybxACzfpMlPdnwHTEraGkQYIQj15kLBq4hUMrrWCaZCz1g8WK9rm09wlxJbe-oPq-1cA/exec"
# =====================================================================

# Colab Flow အဆင်ပြေစေရန် Setup
nest_asyncio.apply()
logging.basicConfig(level=logging.INFO)

# Gemini Client Setup
client_gemini = genai.Client(api_key=GEMINI_API_KEY)

async def handle_image(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("📸 ဓာတ်ပုံကို လက်ခံရရှိပါပြီ။ AI က Color Number, No.Bales နှင့် Yards အားလုံးကို အစဉ်လိုက် ဖတ်နေပါတယ်၊ ခေတ္တစောင့်ပေးပါ...")

    photo_file = await update.message.photo[-1].get_file()
    photo_url = photo_file.file_path
    img_data = requests.get(photo_url).content

    with open("temp_image.png", "wb") as f:
        f.write(img_data)

    try:
        # Gemini 2.5 Flash သို့ ပုံပို့၍ ညွှန်ကြားချက် ပေးခြင်း
        raw_image = client_gemini.files.upload(file="temp_image.png")

        prompt = """
        ဒီဓာတ်ပုံထဲမှာ အထည်လိပ်တွေ အတန်းလိုက် ရှိနေပြီး ပုံပေါ်မှာ စာသားအပိုတွေလည်း ရေးထားတတ်ပါတယ်။
        အချက်အလက်များကို အောက်ပါအတိုင်း သေချာ ခွဲခြားဖတ်ပေးပါ-

        ၁။ Color Number: တံဆိပ် (Label) တွေရဲ့ အရှေ့ဆုံးက ကုဒ်နံပါတ်ကို ရှာပါ။ ဥပမာ - '26.6901...' ဆိုရင် '26' ဖြစ်ပါတယ်။

        ၂။ No. Bales: ပုံရဲ့ အပေါ်နားမှာ 'Bal .15' သို့မဟုတ် 'Bal.15' စသဖြင့် စာလုံးကြီးနဲ့ ရေးထည့်ထားတဲ့ စာသားထဲက ဂဏန်း (ဥပမာ - '15') ကို ဖတ်ပေးပါ။ 'Bal' သို့မဟုတ် 'Bal.' ဆိုတဲ့ စာလုံးတွေ မပါစေဘဲ ဂဏန်း သက်သက်ပဲ ယူရပါမယ်။ အကယ်၍ ပုံထဲမှာ Bal နံပါတ် လုံးဝ ရှာမတွေ့ရင် 'အလွတ်' ထားခဲ့ပါ။

        ၃။ Yards: အထည်လိပ်တစ်ခုချင်းစီရဲ့ 'YDS' အရှေ့က ဂဏန်း (Yards) တွေကို ဓာတ်ပုံရဲ့ ဘယ်ဘက်အစွန်းဆုံးလိပ်ကနေ ညာဘက်အစွန်းဆုံးလိပ်အထိ အစဉ်လိုက်အတိုင်း ဖတ်ပေးပါ။

        ရလာတဲ့ အချက်အလက်တွေကို Google Sheet ထဲ ဘေးတိုက် ဝင်သွားစေဖို့အတွက် အောက်ပါအတိုင်း ကော်မာ (,) လေးတွေပဲ ခြားပြီး စာကြောင်း တစ်ကြောင်းတည်းနဲ့ပဲ ပြန်ပေးပါ။
        ပုံစံ - [Color], [Bales No], [Yards 1], [Yards 2], [Yards 3]...

        အခြား စာသားအပိုတွေ လုံးဝ မပါစေရ။ နမူနာ ပုံစံအတိုင်း ကွက်တိ ပြန်ပေးပါ -
        26, 15, 50, 55, 57, 54
        """

        response = client_gemini.models.generate_content(
            model='gemini-2.5-flash',
            contents=[raw_image, prompt]
        )
        ai_result = response.text.strip()

        # ကော်မာ ခြားပြီး Row တစ်ခုတည်းအဖြစ် ဒေတာ ခွဲထုတ်ခြင်း
        row_data = [data.strip() for data in ai_result.split(',')]
        rows_to_send = [row_data]

        # Google Sheet (Web App URL) သို့ လှမ်းပို့ခြင်း
        response_sheet = requests.post(GOOGLE_WEBAPP_URL, json=rows_to_send)

        if response_sheet.status_code == 200:
            await update.message.reply_text(f"✅ အောင်မြင်ပါသည်။ Google Sheet ထဲသို့ စာရင်းသွင်းပေးပြီးပါပြီ။\n📊 AI ဖတ်မိသောစနစ် - {ai_result}")
        else:
            await update.message.reply_text(f"❌ Google Sheet သို့ ဒေတာပို့ရန် အဆင်မပြေပါ။")

        os.remove("temp_image.png")

    except Exception as e:
        await update.message.reply_text(f"❌ အမှားအယွင်းတစ်ခု ရှိသွားပါတယ်ဗျာ။ Error: {str(e)}")

def main():
    # python-telegram-bot ဗားရှင်းအသစ်အတွက် တည်ဆောက်ပုံစံ
    application = Application.builder().token(TELEGRAM_TOKEN).build()
    application.add_handler(MessageHandler(filters.PHOTO, handle_image))

    print("🤖 Telegram Bot (စနစ်သစ်-အဆင့်မြင့်) စတင်လည်ပတ်နေပါပြီ... (ပုံပို့ပြီး စမ်းသပ်နိုင်ပါပြီ)")
    application.run_polling(close_loop=False)

if __name__ == '__main__':
    main()